### PR TITLE
Typed events

### PR DESCRIPTION
**Pull request by ibaca**
**(not mergeable)**
Hi! this issue is the actual issue that is motivating me to contribute to this project 😛. 

This lib is going to be really useful whenever elemental2 gets stable and people need to create UI without using widgets. Elemental2 it's going to be a pretty raw map from the browser API so this kind of libs that generates a more user-friendly API over elemetal2 it's a necessity.

I'm experimenting with typed events using a uniform API thanks with RxJava (https://github.com/intendia-oss/rxgwt/blob/master/core/src/main/java/com/intendia/rxgwt/elemental2/RxElemental2.java). I have been trying out different strategies in the last years and one of my conclusions is that those @EventHandler bindings (I actually use the UiBinder @UiHandler) are usually not the best strategy. Those helpers methods just avoid the programmatically binding method call (so in your code something like ```EventType.someEvent.register(someElement, () -> actualMethod());``` and this methods is so simple and explicit that IMO doesn't worth hiding it. But, and this is the actual reason to not using @EventHandler, whenever you get an actual lib for bindings (RxJava in this case) exposing always the source is a necessity. This also has the advantage to avoid the use of the UiHandler MVP strategy (https://dev.arcbees.com/gwtp/core/presenters/view-with-ui-handlers.html) because you always exposes observable UI elements in the view, so it is always presenter responsibility to subscribe to the view element. And finally (maybe apply more to rxjava) this encourages/facilitates a correct subscription/unsubscription management. This is because the presenter usually has a lifecycle, and you usually only want to add the handlers if various criteria applies like page is visible, user has permission in this action, the form is valid, etc. all this should be  evaluated in the presenter so at the end, always subscribing and only subscribing in the presenter end up been and good practice.

So... 

What I want is that, as this lib is a typesafe (IMO) element builder, to be also a typesafe event subscription library. So this might be the typesafe/user-friendly counterpart of elemental2. Although, I really think that you should separate in another module the templating engine (same project, just different module), so the core of this libs is just typed/user-friendly elemental2 API.

This match perfectly with my lib, rxgwt, which I will just auto-generate a thin RxJava wrapper around this typed events so you can use RxJava over elemental easily. In this pull request, I include a prototype of this typed events as a minor improvement over you already existent EventType.

### CODE REVIEW

**Comment by hpehl** [comment]
Your design looks very interesting! However I'd like to play around with it, to get a better understanding. 

What I like about your PR, is that it doesn't add a dependency to RxGWT, but prepares Elemento to be used together with RxGWT. 
The separation of Elemento into different modules is also a good idea (SoC). 

What I don't like atm is that it drops the `@EventHandler` annotation. But I think I understand the motivation behind it and it might becomes more obvious after I used the new approach.

**Comment by hpehl** [comment]
As this PR is kind of preparation for Elemento to be used together with RxGWT, do you have some sample code (maybe a RxGWT'ified version of the Todo sample)? This would also help to demonstrate the advantages of the new approach.

**Comment by ibaca** [comment]
Yep, I always tend to mix things. Actually removing EventHandler is totally independent, and using RxGWT is independent too. The most important are typed events, but I'm getting motivated by RxGWT to use those typed events and because I think that defining those typed events in this project instead of defining it in RxGWT is a much better approach.

You totally need to see if this actually fix this project, actually, I'm still seeing if the API is fine, as you can see the EvenType<T,V> has 2 generics, the first one is the event type which makes sense and seems ok. But the second one try to be a limitation of the target/source of events, but I thinks that this cannot be actually used because in JS the event can always go up in the node hierarchy, so it is difficult to limit and to be flexible at the same time, maybe it is just better to remove this second generic.

There are various projects using RxGWT (https://github.com/search?q=topic%3Arxgwt&type=Repositories) althought I have not upload many examples of MVP or even Widgets integrated with RX which is a bit diferent. I'm going to create a variant of this 'Todo sample' to demostrate how can be done and why this makes @EventHandler less useful.

Another personal and probably biased things that motivates to remove EventHandler is that it add an unnecesary complexy but worst, it make you not to worry about the programatically API to use events, I know that if you hasn't created EventHandler you probably will make a better event binding mecanism, probably something like I have been pull-requested 😉. I see that premature generators end up producing poor programatics API and I think this libs should have a very nice programatically API, and this programatically API should be the base to the template system or other tools (all very biased, very personal opinion). In the same line, I think that with some minor changes you can use the element builder API pretty similar as you use in the template, but just using java, hehe but this pull request will arrive later.

**Comment by hpehl** [comment]
@ibaca https://github.com/hal/elemento/commit/7ca24525d4e2a1136bac6e36d83983d54382b7c3 is about SoC: It introduces a custom module for HTML templates: `elemento-template`. Now `elemento-core` is only about the builder API, events and static helper methods.

**Pull request merged**
